version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DB_NAME=securewallet
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - securewallet-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - securewallet-network

networks:
  securewallet-network:
    driver: bridge

volumes:
  mongodb_data: